MQTT_BROKER = "10.108.33.123"

TERMINAL_TOPIC = "/terminal/"
CHECKOUT_TOPIC = "/checkout/"
GREETING_TOPIC = "/greeting/"
FAREWELL_TOPIC = "/farewell/"

RESPONSE_SUFFIX = "resp/"

STATUS_OK = "OK"
STATUS_NOK = "NOK"
