import type {Metadata} from "next";
import QueryProvider from "@/lib/queryClient";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <QueryProvider>
      <body>
      <nav className="navbar navbar-expand-lg navbar-dark bg-gray-100 p-4">
        <div className="flex flex-wrap items-center text-l text-gray-600">
          <div className={'flex flex-wrap items-center space-x-8'}>
            <span className={'text-xl text-black px-10'}>Admin</span>
            <Link className={'hover:text-black'} href="/">Produkty</Link>
            <Link className={'hover:text-black'} href="/add-product">Dodaj produkt</Link>
            <Link className={'hover:text-black'} href="/">Magazyn</Link>
          </div>
        </div>
      </nav>
      {children}
      </body>
    </QueryProvider>
    </html>
  );
}
